### ISSUE TITLE
Don't fail when optional secret is not found 

### ISSUE THREAD

**Issue by razvan-agape** [doitintl/kube-secrets-init#49]
When the pod manifest defines an environment variable using this format, the mutating webhook fails.
```
envFrom:
- secretRef:
    name: <secret-name>
    optional: true
```
or
```
env:
  valueFrom:
    secretKeyRef:
      name: <secret-name>
      key: <key>
      optional: true
```
So, normally, if the secret is not found, kubernetes starts the pod as the secret is marked as `optional`. However, the `kube-secrets-init` mutating webhook is failing the mutating request, blocking pod scheduling (which normally should work).
In theory, kube-secrets-init should not break the normal kubernetes functionality.
